name: flutter_dream_or_reality
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  bottom_navigation_bar: ^1.0.1
  fl_chart: ^0.68.0
  flutter:
    sdk: flutter
  http: ^1.2.1
  table_calendar: ^3.1.1
  shared_preferences: ^2.0.13
  intl: ^0.19.0

flutter:
  uses-material-design: true
  assets:
    - assets/img/illustration/developer.png
    - assets/img/icon/home.png
    - assets/img/icon/document.png
    - assets/img/icon/chat.png
    - assets/img/icon/notebook.png
    - assets/img/icon/user.png
    - assets/img/illustration/test_start.png
    - assets/json/data.json
  fonts:
    - family: PartialSansKR
      fonts:
        - asset: assets/fonts/PartialSansKR-Regular.otf